In [2]:
import pandas as pd
from geopy.distance import geodesic
from datetime import datetime

In [3]:
df = pd.read_csv("./dubai_cold_coffee_spots_clean.csv")

In [4]:
df.head()

,name,lat,lng,type,rating,opening_time,closing_time
0,Brewed Awakening,25.207773,55.290559,cart,4.3,09:00,23:00
1,Chill & Spill,25.248509,55.301298,truck,4.7,08:00,20:00
2,Frosty Mug,25.152942,55.295840,cafe,4.9,06:00,21:00
3,Caffeine Cartel,25.217613,55.346531,cart,3.7,10:00,23:00
4,The Bean Scene,25.154320,55.340818,cafe,4.9,10:00,20:00

In [5]:
user_location = (25.2,55.2)
spot_location = (25.207773,55.290559)


round(geodesic(user_location,spot_location).km,2)

9.17

In [6]:
def calculate_dis(user_location,spot_location):
    return round(geodesic(user_location,spot_location).km,2)

In [7]:
df["maxdis"] = df.apply(lambda row: calculate_dis(user_location,(row["lat"],row["lng"])),axis=1)

In [8]:
# max_dis = 8
# df = df[df["maxdis"] <= 8]

In [9]:
df.sort_values(by="maxdis").head()

,name,lat,lng,type,rating,opening_time,closing_time,maxdis
46,The Roasted Route,25.180392,55.254501,cafe,4.3,08:00,23:00,5.91
20,Brrrista,25.173272,55.252322,cafe,4.0,06:00,23:00,6.05
6,Espresso Express,25.178230,55.256539,cart,4.9,09:00,20:00,6.19
41,Shot Stop,25.235518,55.250343,cafe,5.0,08:00,22:00,6.42
5,Cool Beans,25.192334,55.263833,cafe,4.8,09:00,21:00,6.49

In [10]:
def is_open_now(opening_time,closing_time):
    current_time = datetime.now().strftime("%H:%M")
    return opening_time <= current_time <= closing_time

df["is_open"] = df.apply(lambda row: is_open_now(row["opening_time"],row["closing_time"]),axis=1)

In [11]:
df

,name,lat,lng,type,rating,opening_time,closing_time,maxdis,is_open
0,Brewed Awakening,25.207773,55.290559,cart,4.3,09:00,23:00,9.17,True
1,Chill & Spill,25.248509,55.301298,truck,4.7,08:00,20:00,11.54,False
2,Frosty Mug,25.152942,55.295840,cafe,4.9,06:00,21:00,10.98,True
3,Caffeine Cartel,25.217613,55.346531,cart,3.7,10:00,23:00,14.90,True
4,The Bean Scene,25.154320,55.340818,cafe,4.9,10:00,20:00,15.07,False
5,Cool Beans,25.192334,55.263833,cafe,4.8,09:00,21:00,6.49,True
6,Espresso Express,25.178230,55.256539,cart,4.9,09:00,20:00,6.19,False
7,Mocha Motion,25.159676,55.337032,truck,4.2,08:00,23:00,14.52,True
8,Frozen Grind,25.191297,55.335197,cart,4.1,06:00,23:00,13.66,True
9,Perk Up Cafe,25.246448,55.272767,cart,4.3,06:00,22:00,8.96,True
10,The Daily Brew,25.233261,55.330552,cart,4.0,06:00,21:00,13.66,True
11,Latte on the Go,25.248106,55.304331,cart,3.5,10:00,20:00,11.79,False
12,Bean There,25.179933,55.326601,cafe,4.2,08:00,20:00,12.95,False
13,Sip Stop,25.200194,55.297612,cart,4.6,08:00,22:00,9.84,True
14,Iced & Easy,25.170497,55.311298,cafe,3.6,09:00,23:00,11.68,True
15,Grind House,25.203164,55.304382,cart,4.6,09:00,21:00,10.53,True
16,Arctic Brew,25.228260,55.281833,cart,4.8,09:00,22:00,8.82,True
17,Quick Drip,25.243381,55.312097,cart,3.6,07:00,22:00,12.28,True
18,Mug Life,25.220186,55.289355,truck,3.5,07:00,21:00,9.28,True
19,Flat White Truck,25.179104,55.348576,cart,3.9,09:00,23:00,15.15,True
20,Brrrista,25.173272,55.252322,cafe,4.0,06:00,23:00,6.05,True
21,Chai Chiller,25.218065,55.269152,cafe,4.4,06:00,23:00,7.25,True
22,Caffeinated Camel,25.191213,55.269632,cart,4.7,09:00,20:00,7.09,False
23,Desert Drip,25.161236,55.259174,cafe,3.8,06:00,23:00,7.35,True
24,Java Oasis,25.159588,55.305825,cart,4.5,10:00,23:00,11.57,True
25,Frost & Found,25.190576,55.336748,truck,4.6,10:00,20:00,13.82,False
26,Shake Shack Cafe,25.239039,55.307756,cart,3.7,06:00,23:00,11.69,True
27,Cooler Beans,25.212366,55.269280,cart,5.0,06:00,21:00,7.12,True
28,Nomad Brew,25.239391,55.306152,truck,4.9,09:00,21:00,11.55,True
29,Pulse Cafe,25.182038,55.336626,cart,4.4,09:00,20:00,13.91,False
30,Buzz Station,25.201734,55.318113,cart,4.4,07:00,22:00,11.91,True
31,Bean Bazaar,25.198350,55.305205,truck,4.9,08:00,23:00,10.60,True
32,Sippin’ Point,25.244079,55.331386,cart,4.4,08:00,20:00,14.11,False
33,The Ice Press,25.191494,55.314447,cafe,4.9,09:00,20:00,11.57,False
34,The Chill Spot,25.209224,55.304276,cafe,4.8,06:00,23:00,10.56,True
35,Velvet Roast,25.186886,55.348506,cafe,3.7,08:00,23:00,15.04,True
36,Cafe Mirage,25.166434,55.319951,cart,3.6,09:00,22:00,12.65,True
37,Iced Rush,25.172374,55.271237,truck,4.9,06:00,21:00,7.81,True
38,Snowy Shot,25.230627,55.265882,truck,4.8,06:00,21:00,7.46,True
39,Café Breeze,25.150536,55.338752,cafe,4.5,07:00,22:00,15.02,True
40,Route 66 Coffee,25.216620,55.342005,cart,4.4,06:00,20:00,14.43,False
41,Shot Stop,25.235518,55.250343,cafe,5.0,08:00,22:00,6.42,True
42,Steamy vs Icy,25.213372,55.344224,cafe,3.8,08:00,23:00,14.61,True
43,Latte Land,25.154616,55.309822,cafe,4.1,07:00,22:00,12.16,True
44,Cold Culture,25.248168,55.327985,cafe,4.7,09:00,21:00,13.96,True
45,Brewie Louie,25.245210,55.253333,cafe,4.0,09:00,23:00,7.35,True
46,The Roasted Route,25.180392,55.254501,cafe,4.3,08:00,23:00,5.91,True
47,Carafe Cart,25.199326,55.346555,truck,4.5,06:00,21:00,14.77,True
48,Frozen Feels,25.173230,55.280982,truck,4.7,08:00,23:00,8.68,True
49,Iced Daily,25.213998,55.275438,cart,4.1,08:00,23:00,7.76,True